name: PR Checker

on:
  pull_request:
    branches:
      - 'main'
    types: [synchronize, labeled, opened]
    
concurrency:
  group: pr-check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  Versioning:
    runs-on: macOS-latest
    outputs:
      version: ${{ steps.branch_status.outputs.version }}
      changed: ${{ steps.branch_status.outputs.update }}
    if: |
      contains(toJson(github.event.pull_request.labels.*.name), 'Major :star2:') ||
      contains(toJson(github.event.pull_request.labels.*.name), 'Minor :sparkles:') ||
      contains(toJson(github.event.pull_request.labels.*.name), 'Patch :bug:') ||
      contains(toJson(github.event.pull_request.labels.*.name), 'Skip Version')

    steps:

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org/

    - name: Checkout base branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
        submodules: recursive
        path: sdk

    - name: capture current version
      run: |
        cd sdk
        VERSION=$(sed -n "s/.*s.version *= *'\([^']*\)'.*/\1/p" WoosmapGeofencingCore.podspec)
        if [[ $(grep -o "\." <<< "$VERSION" | wc -l) -eq 1 ]]; then
            VERSION="${VERSION}.0"
        fi
        cat <<EOF > package.json
        {
        "version": "${VERSION}"
        }
        EOF

        echo "SDK_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

    - name: Bump Patch version
      if: contains(toJson(github.event.pull_request.labels.*.name), 'Patch :bug:')
      run: |
        cd sdk
        npm version patch --git-tag-version false
        echo "SDK_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

    - name: Bump Minor version
      if: contains(toJson(github.event.pull_request.labels.*.name), 'Minor :sparkles:')
      run: |
        cd sdk
        npm version minor --git-tag-version false
        echo "SDK_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
        
    - name: Cleanup base
      run: |
        rm -rf sdk

    - name: Checkout PR source branch
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
        
    - name: Check whatsnew.md update
      id: whatsnew
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
              files=$(git diff --name-only -r HEAD^1 HEAD | xargs)
          else
              files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)
          fi
        echo "Changed files: $files"
        if echo "$files" | grep -q "WHATSNEW.md"; then
          echo "passed=true" >> $GITHUB_OUTPUT
        else
          echo "passed=false" >> $GITHUB_OUTPUT
        fi

    - name: Fail if WHATSNEW.md not updated
      if: ${{ steps.whatsnew.outputs.passed == 'false' }}
      run: |
        echo "::error::You missed updating WHATSNEW.md with the latest changes."
        exit 1

    - name: Refetch PR source branch
      uses: actions/checkout@v3
      with:
        ref: "${{ github.head_ref || github.ref_name }}"
        submodules: recursive

    - name: Update version for SDK
      run: |
      
        sed -i "" -e "3 s/.*/  s.version = '${SDK_VERSION}'/" WoosmapGeofencingCore.podspec || exit 1
        sed -i "" -e "s/MARKETING_VERSION \= [^\;]*\;/MARKETING_VERSION = $SDK_VERSION;/" WoosmapGeofencingCore.xcodeproj/project.pbxproj

    - name: Check if branch is dirty
      id: branch_status
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "update=true" >> "$GITHUB_OUTPUT"
        else
          echo "update=false" >> "$GITHUB_OUTPUT"
        fi
        echo "version=$SDK_VERSION" >> "$GITHUB_OUTPUT"
    
    # - name: Run test
    #   run: |
    #     xcodebuild test \
    #       -project WoosmapGeofencingCore.xcodeproj \
    #       -scheme WoosmapGeofencingCoreTests \
    #       -sdk iphonesimulator \
    #       -destination "platform=iOS Simulator,OS=latest,name=iPhone 16" || exit 1

    

  Set_version:
      runs-on: ubuntu-latest
      needs: Versioning
      if: ${{ needs.Versioning.outputs.changed == 'true' }}
      steps:

        - name: Refetch PR source branch
          uses: actions/checkout@v3
          with:
            ref: "${{ github.head_ref || github.ref_name }}"
            
    
        - name: Update version for SDK
          env:
            SDK_VERSION: ${{ needs.Versioning.outputs.version }}
          run: |
            sed -i "3 s/.*/  s.version = '${SDK_VERSION}'/" WoosmapGeofencingCore.podspec || exit 1
            sed -i "s/MARKETING_VERSION \= [^\;]*\;/MARKETING_VERSION = $SDK_VERSION;/" WoosmapGeofencingCore.xcodeproj/project.pbxproj
        
        - name: Commit and push changes
          uses: devops-infra/action-commit-push@master
          env:
            SDK_VERSION: ${{ needs.Versioning.outputs.version }}
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            commit_message: "Updated ${{ env.SDK_VERSION }}"
            commit_prefix: "[AUTO]"
            force: false


  pre-publish:
    runs-on: ubuntu-latest
    needs: Versioning
    outputs:
      sdk_version: ${{ steps.extract_version.outputs.sdk_version }}

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Fetch SDK version from Podspec
        id: extract_version
        run: |
          SDK_VERSION=$(sed -n "s/.*s.version *= *'\([^']*\)'.*/\1/p" WoosmapGeofencingCore.podspec)
          echo "SDK version: $SDK_VERSION"
          echo "sdk_version=$SDK_VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.extract_version.outputs.sdk_version }}
          git push origin ${{ steps.extract_version.outputs.sdk_version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_version.outputs.sdk_version }}
          body_path: WHATSNEW.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cocoa-pod:
    runs-on: macos-15
    needs: pre-publish

    steps:
      - name: Set up Ruby and CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Lint podspec
        run: |
          pod lib lint WoosmapGeofencing.podspec --allow-warnings

      - name: Push to CocoaPods trunk
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          mkdir -p ~/.cocoapods/trunk
          cat <<EOF > ~/.cocoapods/trunk/config.json
          {
            "trunk_token": "${COCOAPODS_TRUNK_TOKEN}"
          }
          EOF

          pod trunk me
          # pod trunk push WoosmapGeofencing.podspec --allow-warnings

      - name: Cleanup credentials
        if: ${{ always() }}
        run: |
          rm -rf ~/.cocoapods
